final_folder = r"Final"
scan_folder = r"Scan"
result_folder = r"Result"
conversion_sheet = r"Conversion.xlsx"
docdata_sheet = r"document_data.csv"
docdata_backup_sheet = r"document_data_backup.csv"

blank_page = r"BlankPage.pdf"
labeled_path = r"Labeled"
temp_png = r"Temporary\guess_temp.PNG"
output_txt = r"Temporary\guess_output.txt"
temp_prediction_png = r"Temporary\TempDocPng"
temp_prediction_png_second = r"Temporary\TempDocPng2"
temp_prediction_png_third = r"Temporary\TempDocPng3"

completed_path = r"Completed"
pdf_dataset = r"Dataset\PDFFull"
text_dataset = r"Dataset\TextData"
text_dataset_file = r"Dataset\TextData.txt"
pdf_normal_dataset = r"Dataset\PDFNormal"
pdf_renewal_dataset = r"Dataset\PDFRenewalUpdate"